"""Deterministic digest gates; stdlib-only, including CLI integration."""
import importlib.util
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest

SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "validate-digest.py"


def item(n, marker="-"):
    return f"{marker} 重要变化与影响 [来源](https://example.com/news/{n})"


def release(n, explanation="修复内存问题，部署用户应升级。", owner="org"):
    return (f"- **{owner}/repo{n}** `v1.2.3` — {explanation} "
            f"[发布](<https://github.com/{owner}/repo{n}/releases/tag/v1.2.3>)")


class DigestValidatorTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        spec = importlib.util.spec_from_file_location("validate_digest", SCRIPT)
        assert spec is not None and spec.loader is not None
        cls.module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(cls.module)

    def errors(self, text, mode="daily"):
        return self.module.validate(text, mode)

    def valid(self, text, mode="daily"):
        self.assertEqual([], self.errors(text, mode))

    def invalid(self, text, code, mode="daily"):
        errors = self.errors(text, mode)
        self.assertTrue(any(code in error for error in errors), errors)

    def test_daily_boundary_both_markers(self):
        text = "## 今日要闻\n" + "\n".join(item(n, "•" if n % 2 else "-") for n in range(12))
        self.valid(text)
        self.invalid(text + "\n" + item(12), "item-limit")

    def test_weekly_boundary(self):
        text = "\n".join(item(n) for n in range(18))
        self.valid(text, "weekly")
        self.invalid(text + "\n" + item(18), "item-limit", "weekly")
        self.invalid(text, "item-limit", "daily")

    def test_nested_bullets_not_top_level(self):
        text = "\n".join(item(n) + "\n  - 影响说明" for n in range(12))
        self.valid(text)

    def test_valid_link_forms_and_continuations(self):
        for link in ("[来源](https://example.com/a)", "[来源](<https://example.com/a>)",
                     "<https://example.com/a>", '[来源](https://example.com/a "Title")',
                     "[来源](https://example.com/a_(b))", "[来源](https://例子.中国/中文)"):
            with self.subTest(link=link):
                self.valid("• 重要新闻\n  " + link)

    def test_missing_or_invalid_links(self):
        for link in ("", "https://example.com/raw", "[来源](javascript:alert(1))",
                     "[来源](https:///missing)", "[来源](https://)",
                     "[来源](https://bad host/a)", "[来源](ftp://example.com/a)",
                     "[来源](https://example.com:bad/a)"):
            with self.subTest(link=link):
                self.invalid("- 新闻 " + link, "source-link")

    def test_duplicate_urls_and_attribution(self):
        self.invalid(item(1) + "\n" + item(1, "•"), "duplicate-url")
        self.invalid("- 新闻 [甲](https://example.com/a) [乙](<https://example.com/a>)", "duplicate-url")
        self.valid(item(1) + "\n---\n🤖 Generated by tech-news-digest | <https://example.com/news/1>")
        self.invalid(item(1) + "\n---\n" + item(1), "duplicate-url")
        self.invalid(item(1) + "\n参考：https://example.com/news/1", "duplicate-url")

    def test_score_prefixes(self):
        for prefix in ("🔥12 | ", "**🔥 9.5** | ", "quality_score: 12 | ", "[score: 10] ", "质量分：9 | "):
            with self.subTest(prefix=prefix):
                self.invalid("- " + prefix + "新闻 [源](https://example.com)", "quality-score")
        self.valid("- 新基准得分 95，实测结果 [源](https://example.com)")

    def test_fake_daily_growth(self):
        for growth in ("+56/day", "+1,234/日", "+1.2K / day", "+ 23 / 日"):
            with self.subTest(growth=growth):
                self.invalid(item(1) + " " + growth, "daily-growth")
        self.valid(item(1) + " 总星数 1,234，同比增长 12%")

    def test_legacy_headings_and_operational_footer(self):
        for heading in ("## 📢 KOL Updates", "**🐙 GitHub Trending**", "## KOL 动态", "## GitHub 趋势"):
            with self.subTest(heading=heading):
                self.invalid(heading + "\n" + item(1), "legacy-heading")
        for footer in ("📊 Data Sources: RSS 5 | Twitter 2 | Dedup: 7 articles", "📊 数据源：RSS 5 | GitHub 3"):
            self.invalid(item(1) + "\n---\n" + footer, "operational-footer")
        self.valid("## 行业观察\n" + item(1) + " 讨论 GitHub Trending 数据")

    def test_release_caps(self):
        for mode, cap in (("daily", 3), ("weekly", 5)):
            text = "## 📦 GitHub 发布精选\n" + "\n".join(release(n) for n in range(cap))
            self.valid(text, mode)
            self.invalid(text + "\n" + release(cap), "release-limit", mode)

    def test_release_repo_duplicates(self):
        text = "## GitHub Releases\n" + release(1) + "\n" + release(1).replace("v1.2.3", "v1.2.4")
        self.invalid(text, "duplicate-repo")
        self.invalid("## 要闻\n" + release(1) + "\n## 发布精选\n" + release(1).replace("v1.2.3", "v2.0.0"), "duplicate-repo")

    def test_release_explanation_counts_all_characters(self):
        self.valid("## GitHub Releases\n" + release(1, "中" * 80))
        self.invalid("## GitHub Releases\n" + release(1, "中" * 81), "release-length")
        self.invalid("## GitHub Releases\n" + release(1, "中" + "A" * 80), "release-length")
        self.valid("## GitHub Releases\n" + release(1, "中" * 80, owner="very-long-repository-owner"))

    def test_release_linked_explanation_still_counts(self):
        text = "## GitHub Releases\n- **org/repo** `v1.0` — [" + "中" * 81 + "](https://github.com/org/repo/releases/tag/v1.0)"
        self.invalid(text, "release-length")
        self.valid(text.replace("中" * 81, "中" * 80))

    def test_repo_label_identification_without_github_url(self):
        text = "## Releases\n- **org/repo** v1.0 — 修复问题 [源](https://example.com/one)\n- **ORG/REPO** v2.0 — 改善性能 [源](https://example.com/two)"
        self.invalid(text, "duplicate-repo")

    def test_chinese_legacy_heading_and_footer(self):
        self.invalid("## KOL动态\n" + item(1), "legacy-heading")
        self.invalid(item(1) + "\n📊 数据来源：RSS 10 | GitHub 3", "operational-footer")

    def test_invalid_hostname(self):
        for url in ("https://example..com/a", "https://%invalid/a", "https://-invalid.com/a"):
            self.invalid("- 新闻 [源](" + url + ")", "source-link")

    def test_combined_tools_section_not_all_releases(self):
        text = "## 工具与开源 / Tools & Releases\n" + item(1) + "中" * 100
        text += "\n" + "\n".join(item(n) for n in range(2, 7))
        self.valid(text)
        self.invalid(text + "\n" + release(1, "中" * 81), "release-length")

    def test_experiment_exemption_is_narrow(self):
        self.valid("## 下周实验\n- 建议试用本地模型，对比内存占用。")
        self.valid("## Next-week experiments\n• Try a local model and measure latency.", "weekly")
        self.invalid("## 下周实验\n- 公司发布了新模型。", "source-link")
        self.invalid("## 要闻\n- 建议关注这家公司的新模型。", "source-link")
        self.invalid("## 下周实验\n- 建议试用 [源](https:///bad)", "source-link")

    def test_current_weekly_validation_headings(self):
        for title in ("下周验证", "下周验证清单", "Next-week validation"):
            self.valid("## " + title + "\n- 建议对比模型延迟。", "weekly")
        self.valid("## 下周验证（拟议，尚未执行）\n- **延迟是否下降** — 最小测试：固定输入；指标：P95。", "weekly")
        self.invalid("## 下周验证\n- 模型已经发布。", "source-link", "weekly")
        self.invalid("## 关键人物动态\n" + item(1), "legacy-heading")

    def test_canonical_duplicate_urls_preserve_real_query(self):
        self.invalid("- 新闻 [源](https://example.com/a?id=2&utm_source=x#part)\n- 新闻 [源](https://example.com/a?fbclid=z&id=2&gclid=y)", "duplicate-url")
        self.valid("- 新闻 [源](https://example.com/a?id=2)\n- 新闻 [源](https://example.com/a?id=3)")

    def test_exact_editorial_section_caps(self):
        for title, mode, cap in (("值得读", "daily", 1), ("值得读", "weekly", 2),
                                 ("项目发现", "daily", 1), ("值得试", "weekly", 2),
                                 ("可行动", "daily", 2), ("本周主题", "weekly", 3),
                                 ("下周验证清单", "weekly", 3)):
            text = "## " + title + "\n" + "\n".join(item(n) for n in range(cap))
            self.valid(text, mode)
            self.invalid(text + "\n" + item(cap), "section-limit", mode)

    def test_empty_is_not_deliverable(self):
        self.invalid("# Daily digest\n", "empty-digest")

    def test_cli_success_failure_and_io_errors(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "digest.md"
            path.write_text(item(1), encoding="utf-8")
            command = [sys.executable, str(SCRIPT), "--input", str(path), "--mode", "daily"]
            result = subprocess.run(command, capture_output=True, text=True)
            self.assertEqual(0, result.returncode, result.stderr)
            self.assertIn("PASS", result.stdout)
            path.write_text("- 没有来源", encoding="utf-8")
            result = subprocess.run(command, capture_output=True, text=True)
            self.assertEqual(1, result.returncode)
            self.assertIn("source-link", result.stderr)
            path.unlink()
            result = subprocess.run(command, capture_output=True, text=True)
            self.assertEqual(2, result.returncode)
            self.assertNotIn("Traceback", result.stderr)


if __name__ == "__main__":
    unittest.main()
